### ISSUE TITLE
Not support lumen routes

### ISSUE THREAD

**Issue by huangdijia** [simoebenhida/laravel-intellisense#13]
```
異常: Symfony\Component\ErrorHandler\Error\FatalError
信息: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Http\Kernel] is not instantiable. in /Users/hdj/gitroot/8591/chat-serve/vendor/illuminate/container/Container.php:1013
Stack trace:
#0 /Users/hdj/gitroot/8591/chat-serve/vendor/illuminate/container/Container.php(814): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/hdj/gitroot/8591/chat-serve/vendor/illuminate/container/Container.php(687): Illuminate\Container\Conta
```

```
異常: Symfony\Component\ErrorHandler\Error\FatalError
信息: Uncaught Error: Call to a member function getRoutes() on array in Command line code:1
Stack trace:
#0 {main}
  thrown
```

**Comment by simoebenhida** [comment]
Thanks for reporting the issue!
