### ISSUE TITLE
Error in Lumen

### ISSUE THREAD

**Issue by gpibarra** [simoebenhida/laravel-intellisense#38]
```
local.ERROR: Symfony\Component\ErrorHandler\Error\FatalError: Uncaught Error: Call to undefined function app_path() in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code:1
Stack trace:
#0 \\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(80): Symfony\Component\ErrorHandler\Error\FatalError->__construct(''Uncaught Error...', '0', '['type' => 1, '...', '0', '???', '???')
#1 \\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(67): Laravel\Lumen\Application->fatalErrorFromPhpError('['type' => 1, '...', '0')
#2 \\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#3 \\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(0): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure:\\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php:54-56}()
#4 {main} {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Call to undefined function app_path() in Command line code:1
Stack trace:
#0 {main}
  thrown at Command line code:1)
[stacktrace]
#0 \\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php(80): Symfony\\Component\\ErrorHandler\\Error\\FatalError->__construct(''Uncaught Error...', '0', '['type' => 1, '...', '0', '???', '???')
#1 \\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php(67): Laravel\\Lumen\\Application->fatalErrorFromPhpError('['type' => 1, '...', '0')
#2 \\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php(55): Laravel\\Lumen\\Application->handleShutdown()
#3 \\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php(0): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure:\\\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php:54-56}()
#4 {main}
"} 
```

**Comment by simoebenhida** [comment]
Thanks for reporting the issue! Will give it a try on Lumen!
